app/routes/product_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models.product import Product, ProductType
from database import db

import os
from werkzeug.utils import secure_filename

from helpers import login_required

from flask import current_app

product_routes = Blueprint('product_routes', __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@product_routes.route('/add_product', methods=['GET', 'POST'])
@login_required
def add_product():
    if request.method == 'GET':
        return render_template('addproduct.html')

    elif request.method == 'POST':
        product_name = request.form.get('product_name')
        product_image_file = request.files.get('product_image')
        code = request.form.get('code')
        category = request.form.get('category', 'Bahan')
        storage = request.form.get('storage')
        stock = request.form.get('stock')
        details = request.form.get('details')

        product_image_path = None

        # Save the product image if provided
        if product_image_file and allowed_file(product_image_file.filename):
            filename = secure_filename(product_image_file.filename)
            product_image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            product_image_file.save(product_image_path)

        product_by_code = Product.query.filter_by(code=code).first()

        if product_by_code:
            flash('Product code already exists. Choose another one.')
            return redirect(url_for('product_routes.add_product'))

        # Store product details in database
        new_product = Product(
            product_name=product_name,
            product_image=product_image_path,
            code=code,
            category=category,
            storage=storage,
            stock=stock,
            details=details
        )
        db.session.add(new_product)
        db.session.commit()

        flash('Product added successfully!')
        return redirect(url_for('product_routes.get_productlist'))

    return render_template('addproduct.html',  products=products, pagination=pagination)

@product_routes.route('/productlist', methods=['GET'])
@login_required
def get_productlist():
    products = Product.query.all()
    return render_template('productlist.html', products=products)
    # page = request.args.get('page', 1, type=int)
    # per_page = request.args.get('per_page', 10, type=int)

    # search_term = request.args.get('search', '')
    # query = Product.query

    # if search_term:
    #     search_pattern = f"%{search_term}%"
    #     query = query.filter(
    #         Product.product_name.ilike(search_pattern) |
    #         Product.category.ilike(search_pattern)
    #     )

    # pagination = query.paginate(page=page, per_page=per_page, error_out=False)
    # products = pagination.items

    # return render_template('productlist.html', products=products, pagination=pagination)

@product_routes.route('/productdetails/<int:id>')
@login_required
def product_details(id):
    product = Product.query.get(id)
    if not product:
        flash("Product not found", "error")
        return redirect(url_for('product_routes.get_productlist'))

    return render_template('productdetails.html', product=product)

@product_routes.route('/editproduct/<int:id>', methods=['GET', 'POST'])
@login_required
def editproduct(id):

    product = Product.query.get(id)

    if not product:
        flash("Product not found", "error")
        return redirect(url_for('product_routes.get_productlist'))
    
    if request.method == 'GET':
        return render_template('editproduct.html', product=product)
    
    if request.method == 'POST':
        product_name = request.form.get('product_name')
        code = request.form.get('code')
        category =  request.form.get('category')
        storage = request.form.get('storage')
        stock = request.form.get('stock')
        details = request.form.get('details')

        product.product_name = product_name if product_name else product.product_name
        product.code = code if code else product.code
        product.category = category
        product.storage = storage
        product.stock = stock
        product.details = details

        product_image = request.files.get('product_image')

        if product_image and allowed_file(product_image.filename):
            if product.product_image and os.path.exists(product.product_image):
                os.remove(product.product_image)
                
            filename = secure_filename(product_image.filename)
            product_image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            product_image.save(product_image_path)
            product.product_image = product_image_path
        
        db.session.commit()

        flash("Product updated successfully!", "success")
        return redirect(url_for('product_routes.get_productlist'))

@product_routes.route('/delete_product/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_product(id):
    product = Product.query.get(id)
    
    if not product:
        flash("Product not found", "error")
        return redirect(url_for('product_routes.get_productlist'))

    db.session.delete(product)
    db.session.commit()

    flash("Product deleted successfully!", "success")
    return redirect(url_for('product_routes.get_productlist'))

app/routes/user_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify
from models.user import User, UserRole
from database import db
from werkzeug.security import generate_password_hash, check_password_hash

import os
from werkzeug.utils import secure_filename

from helpers import login_required

from flask import current_app

user_routes = Blueprint('user_routes', __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@user_routes.route('/hello', methods=['GET'])
def hello():
    return "Hello!!"

@user_routes.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')

        # Check if user already exists
        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already exists. Choose another one.')
            return redirect(url_for('user_routes.signup'))

        # Store user details in database
        new_user = User(
            username=username,
            email=email,
            password=generate_password_hash(password, method='pbkdf2:sha256'),
            role='Mahasiswa'
        )
        db.session.add(new_user)
        db.session.commit()

        flash('Registration successful. Please login.')
        return redirect(url_for('user_routes.signin'))

    return render_template('signup.html')

@user_routes.route('/signin', methods=['GET', 'POST'])
def signin():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()

        if not user or not check_password_hash(user.password, password):
            flash('Incorrect email or password. Please try again.')
            return redirect(url_for('user_routes.signin'))

        session['user_id'] = user.id
        session['username'] = user.username

        flash('Login successful!')
        return redirect(url_for('base_routes.home'))

    return render_template('signin.html')

@user_routes.route('/signout', methods=['GET'])
def signout():
    # Remove the user data from the session if it's there
    session.pop('username', None)
    flash('You have been logged out.')
    return redirect(url_for('user_routes.signin'))

# @user_routes.route('/userlist', methods=['GET'])
# @login_required
# def get_userlist():
#     page = request.args.get('page', 1, type=int)
#     per_page = request.args.get('per_page', 10, type=int)

#     search_term = request.args.get('search', '')
#     query = User.query

#     if search_term:
#         search_pattern = f"%{search_term}%"
#         query = query.filter(
#             User.username.ilike(search_pattern) | 
#             User.full_name.ilike(search_pattern) |
#             User.email.ilike(search_pattern) |
#             User.student_id.ilike(search_pattern) |
#             User.no_hp.ilike(search_pattern)
#         )

#     pagination = query.paginate(page=page, per_page=per_page, error_out=False)
#     users = pagination.items

#     return render_template('userlist.html', users=users, pagination=pagination)

@user_routes.route('/add_user', methods=['GET', 'POST'])
@login_required
def add_user():
    if request.method == 'GET':
        return render_template('adduser.html')

    elif request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        full_name = request.form.get('full_name')
        student_id = request.form.get('student_id')
        role = request.form.get('role', 'Mahasiswa')
        no_hp = request.form.get('no_hp')
        self_photo_file = request.files.get('self_photo')
        card_photo_file = request.files.get('card_photo')

        self_photo_path = None
        card_photo_path = None

        # Save the self photo if provided
        if self_photo_file and allowed_file(self_photo_file.filename):
            filename = secure_filename(self_photo_file.filename)
            self_photo_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            self_photo_file.save(self_photo_path)

        # Save the card photo if provided
        if card_photo_file and allowed_file(card_photo_file.filename):
            filename = secure_filename(card_photo_file.filename)
            card_photo_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            card_photo_file.save(card_photo_path)

        user_by_username = User.query.filter_by(username=username).first()
        user_by_email = User.query.filter_by(email=email).first()
        user_by_student_id = User.query.filter_by(student_id=student_id).first()

        if user_by_username:
            flash('Username already exists. Choose another one.')
            return redirect(url_for('user_routes.add_user'))
        if user_by_email:
            flash('Email already exists. Choose another one.')
            return redirect(url_for('user_routes.add_user'))
        if user_by_student_id:
            flash('Student ID already exists. Choose another one.')
            return redirect(url_for('user_routes.add_user'))

        # Store user details in database
        new_user = User(
            username=username,
            email=email,
            password=generate_password_hash(password, method='pbkdf2:sha256'),
            full_name=full_name,
            student_id=student_id,
            role=role,
            no_hp=no_hp,
            self_photo=self_photo_path,
            card_photo=card_photo_path
        )
        db.session.add(new_user)
        db.session.commit()

        flash('User added successfully!')
        return redirect(url_for('user_routes.get_userlist'))

    return render_template('adduser.html',  users=users, pagination=pagination)

@user_routes.route('/userlist', methods=['GET'])
@login_required
def get_userlist():
    users = User.query.all()
    return render_template('userlist.html', users=users)



@user_routes.route('/edituser/<int:id>', methods=['GET', 'POST'])
@login_required
def edituser(id):
    # Assuming you have a User model that queries users by id
    user = User.query.get(id)
    
    if not user:
        flash("User not found", "error")
        return redirect(url_for('user_routes.get_userlist'))

    if request.method == 'GET':
        return render_template('edituser.html', user=user)

    elif request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        full_name = request.form.get('full_name')
        student_id = request.form.get('student_id')
        role = request.form.get('role', 'Mahasiswa')
        no_hp = request.form.get('no_hp')

        user.username = username
        user.email = email
        user.full_name = full_name if full_name else user.full_name
        user.student_id = student_id if student_id else user.student_id
        user.role = role if role else user.role
        user.no_hp = no_hp if no_hp else user.no_hp

        self_photo_file = request.files.get('self_photo')
        card_photo_file = request.files.get('card_photo')

        if self_photo_file and allowed_file(self_photo_file.filename):
            if user.self_photo and os.path.exists(user.self_photo):
                os.remove(user.self_photo)
                
            filename = secure_filename(self_photo_file.filename)
            self_photo_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            self_photo_file.save(self_photo_path)
            user.self_photo = self_photo_path

        if card_photo_file and allowed_file(card_photo_file.filename):
            if user.card_photo and os.path.exists(user.card_photo):
                os.remove(user.card_photo)
                
            filename = secure_filename(card_photo_file.filename)
            card_photo_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            card_photo_file.save(card_photo_path)
            user.card_photo = card_photo_path

        db.session.commit()

        flash("User updated successfully!", "success")
        return redirect(url_for('user_routes.get_userlist'))

@user_routes.route('/delete_user/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    user = User.query.get(id)
    
    if not user:
        flash("User not found", "error")
        return redirect(url_for('user_routes.get_userlist'))

    db.session.delete(user)
    db.session.commit()

    flash("User deleted successfully!", "success")
    return redirect(url_for('user_routes.get_userlist'))

app/templates/productdetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description" content="POS - Bootstrap Admin Template">
    <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
    <meta name="author" content="Dreamguys - Bootstrap Admin Template">
    <meta name="robots" content="noindex, nofollow">

    <title>AlatLabKu</title>

    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/logo-small.png') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/select2/css/select2.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/owlcarousel/owl.carousel.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap4.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/fontawesome/css/fontawesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/fontawesome/css/all.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <div id="global-loader">
        <div class="whirly-loader"> </div>
    </div>

    <div class="main-wrapper">
        {% include 'navbar.html' %}
        {% include 'sidebar.html' %}

        <div class="page-wrapper">
            <div class="content">
                <div class="page-header">
                    <div class="page-title">
                        <h4>Detail Produk</h4>
                        <h6>Detail Lengkap Produk</h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{ url_for('product_routes.product_details', id=product.id) }}" method="get">
                                    <div class="productdetails">
                                        <ul class="product-bar">
                                            <li>
                                                <h4>Produk</h4>
                                                <h6>{{ product.product_name }}</h6>
                                            </li>
                                            <li>
                                                <h4>Kategori</h4>
                                                <h6>{{ product.category }}</h6>
                                            </li>
                                            <li>
                                                <h4>Tempat Barang</h4>
                                                <h6>{{ product.storage }}</h6>
                                            </li>
                                            <li>
                                                <h4>Stok</h4>
                                                <h6>{{ product.stock }}</h6>
                                            </li>
                                            <li>
                                                <h4>Detail</h4>
                                                <h6><td>{{ product.details|replace("\n", "<br>")|safe }}</td></h6>
                                            </li>
                                            <li>
                                                <h4>Status</h4>
                                                <h6>{% if product.stock and product.stock > 0 %}Tersedia{% else %}Tidak Tersedia{% endif %}</h6>
                                            </li>
                                            <li>
                                                <h4>Ditambahkan Pada</h4>
                                                <h6>{{ product.created_at.strftime('%d %B %Y') }}</h6>
                                            </li>
                                            <li>
                                                <h4>Diperbaharui Pada</h4>
                                                <h6>{{ product.updated_at.strftime('%d %B %Y') }}</h6>
                                            </li>
                                        </ul>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="slider-product-details">
                                    <div class="owl-carousel owl-theme product-slide">
                                        <div class="slider-product">
                                            <img src="{{ url_for('static', filename=product.product_image[7:]) }}" alt="Product Image">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/feather.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/jquery.slimscroll.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <script src="{{ url_for('static', filename='plugins/owlcarousel/owl.carousel.min.js') }}"></script>

    <script src="{{ url_for('static', filename='plugins/select2/js/select2.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

</body>
</html>

app/templates/productlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description" content="POS - Bootstrap Admin Template">
    <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
    <meta name="author" content="Dreamguys - Bootstrap Admin Template">
    <meta name="robots" content="noindex, nofollow">

    <title>AlatLabKu</title>

    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/logo-small.png') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <link rel="stylesheet" href="static/css/animate.css">

    <link rel="stylesheet" href="static/plugins/select2/css/select2.min.css">

    <link rel="stylesheet" href="static/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="static/plugins/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="static/plugins/fontawesome/css/all.min.css">

    <link rel="stylesheet" href="static/css/style.css">
</head>

<body>
    <div id="global-loader">
        <div class="whirly-loader"> </div>
    </div>

    <div class="main-wrapper">
        {% include 'navbar.html' %}
        {% include 'sidebar.html' %}

        <div class="page-wrapper">
            <div class="content">
                <div class="page-header">
                    <div class="page-title">
                        <h4>Daftar Produk</h4>
                        <h6>Kelola Produk</h6>
                    </div>
                    <div class="page-btn">
                        <a href="{{ url_for('product_routes.add_product') }}" class="btn btn-added"> <!-- Adjusted for dynamic routing -->
                            <img src="{{ url_for('static', filename='img/icons/plus.svg') }}" alt="img" class="me-1">Tambah Produk
                        </a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="table-top">
                            <div class="search-set">
                                <div class="search-input">
                                    <a class="btn btn-searchset"><img src="static/img/icons/search-white.svg" alt="img"></a>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-0" id="filter_inputs">
                            <div class="card-body pb-0">
                                <!-- <div class="row">
                                    <div class="col-lg-12 col-sm-12">
                                        <div class="row">
                                            <div class="col-lg col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="">Pilih Nama Produk</label>
                                                    <select class="select">
                                                        <option>Macbook pro</option>
                                                        <option>Orange</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="">Pilih Kategori</label>
                                                    <select class="select">
                                                        <option>Alat</option>
                                                        <option>Bahan</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-1 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <a class="btn btn-filters ms-auto"><img src="static/img/icons/search-whites.svg" alt="img"></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div> -->
                                <div class="row">
                                    <div class="col-lg-2 col-sm-6 col-12">
                                        <div class="form-group">
                                            <input type="text" name="" id="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="table-responsive">
                            <table class="table  datanew">
                                <thead>
                                    <tr>
                                    <th>Foto Produk</th>
                                    <th>Nama Produk</th>
                                    <th>Kode Produk</th>
                                    <th>Kategori</th>
                                    <th>Tempat Barang</th>
                                    <th>Stok</th>
                                    <th>Detail</th>
                                    <th>Status</th>
                                    <th>Ditambahkan Pada</th>
                                    <th>Diperbaharui pada</th>
                                    <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product in products %}
                                        <tr>
                                            <td class="productimgname">
                                                <a href="javascript:void(0);" class="product-img">
                                                    <img src="{{ product.product_image }}" alt="product's image">
                                                </a>
                                            </td>
                                            <td>{{ product.product_name }}</td>
                                            <td>{{ product.code }}</td>
                                            <td>{{ product.category }}</td>
                                            <td>{{ product.storage }}</td>
                                            <td>{{ product.stock }}</td>
                                            <td>{{ product.details|replace("\n", "<br>")|safe }}</td>
                                            <td>
                                                {% if product.stock and product.stock > 0 %}
                                                    <span class="bg-lightgreen badges">Tersedia</span>
                                                {% else %}
                                                    <span class="bg-lightred badges">Tidak Tersedia</span>
                                                {% endif %}
                                            </td>
                                            <td>{{ product.created_at|default("Date not available", true) }}</td>
                                            <td>{{ product.updated_at|default("Date not available", true) }}</td>
                                            <td>
                                                <a class="me-3" href="{{ url_for('product_routes.product_details', id=product.id) }}">
                                                    <img src="static/img/icons/eye.svg" alt="img">
                                                </a>
                                                <a class="me-3" href="{{ url_for('product_routes.editproduct', id=product.id) }}">
                                                    <img src="static/img/icons/edit.svg" alt="img">
                                                </a>
                                                <a class="me-3" href="javascript:void(0);" onclick="confirmDelete('{{ url_for('product_routes.delete_product', id=product.id) }}')">
                                                    <img src="static/img/icons/delete.svg" alt="img">
                                                </a>                                                
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="static/js/jquery-3.6.0.min.js"></script>

    <script src="static/js/feather.min.js"></script>

    <script src="static/js/jquery.slimscroll.min.js"></script>

    <script src="static/js/jquery.dataTables.min.js"></script>
    <script src="static/js/dataTables.bootstrap4.min.js"></script>

    <script src="static/js/bootstrap.bundle.min.js"></script>

    <script src="static/plugins/select2/js/select2.min.js"></script>

    <script src="static/plugins/sweetalert/sweetalert2.all.min.js"></script>
    <script src="static/plugins/sweetalert/sweetalerts.min.js"></script>

    <script src="static/js/script.js"></script>

    <script>
        function confirmDelete(deleteUrl) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = deleteUrl;
                }
            });
        }
    </script>

</body>
</html>